# SFR Backtesting Configuration
# Comprehensive configuration file for SFR arbitrage backtesting engine

# Database Configuration
database:
  host: localhost
  port: 5433
  database: options_arbitrage
  user: trading_user
  password: secure_trading_password
  min_pool_size: 5
  max_pool_size: 20

# Default Target Symbols (Top 10 for SFR backtesting)
target_symbols:
  - SPY    # S&P 500 ETF
  - QQQ    # Nasdaq 100 ETF
  - AAPL   # Apple Inc.
  - MSFT   # Microsoft Corp.
  - NVDA   # NVIDIA Corp.
  - TSLA   # Tesla Inc.
  - AMZN   # Amazon.com Inc.
  - META   # Meta Platforms Inc.
  - GOOGL  # Alphabet Inc.
  - JPM    # JPMorgan Chase & Co.

# Backtesting Periods (predefined options)
periods:
  quick_test: 30      # days
  short_term: 90      # 3 months
  medium_term: 365    # 1 year
  long_term: 1825     # 5 years
  full_cycle: 3650    # 10 years

# Configuration Presets
configurations:
  # Conservative configuration - tight risk controls
  conservative:
    profit_target: 0.75                  # 0.75% minimum profit target
    cost_limit: 100.0                    # $100 maximum cost limit
    volume_limit: 100                    # Minimum 100 volume
    quantity: 1                          # Single contract trades
    call_strike_range_days: 20           # $20 strike range
    put_strike_range_days: 20
    expiry_min_days: 19                  # 19-45 day expiry range
    expiry_max_days: 45
    max_strike_combinations: 3           # Test fewer combinations
    max_expiry_options: 6                # Test fewer expiries
    max_bid_ask_spread_call: 10.0        # $10 max call spread
    max_bid_ask_spread_put: 10.0         # $10 max put spread
    combo_buffer_percent: 0.01           # 1% buffer
    slippage_model: "LINEAR"
    base_slippage_bps: 3                 # 3 basis points
    liquidity_penalty_factor: 1.2       # Higher penalty
    commission_per_contract: 1.50        # Higher commission
    vix_regime_filter: null
    min_vix_level: null
    max_vix_level: 30.0                  # Exclude extreme volatility
    exclude_vix_spikes: true

  # Aggressive configuration - higher volume, more opportunities
  aggressive:
    profit_target: 0.25                  # Lower profit target
    cost_limit: 200.0                    # Higher cost limit
    volume_limit: 50                     # Lower volume requirement
    quantity: 2                          # Larger position size
    call_strike_range_days: 30
    put_strike_range_days: 30
    expiry_min_days: 15                  # Wider expiry range
    expiry_max_days: 60
    max_strike_combinations: 6           # More combinations
    max_expiry_options: 10               # More expiries
    max_bid_ask_spread_call: 30.0        # Allow wider spreads
    max_bid_ask_spread_put: 30.0
    combo_buffer_percent: 0.005          # Smaller buffer
    slippage_model: "IMPACT"             # Market impact model
    base_slippage_bps: 4                 # Higher base slippage
    liquidity_penalty_factor: 1.0       # Standard penalty
    commission_per_contract: 0.75        # Lower commission (bulk pricing)
    vix_regime_filter: null
    min_vix_level: null
    max_vix_level: null
    exclude_vix_spikes: false

  # Low VIX environment optimization
  low_vix:
    profit_target: 0.50
    cost_limit: 150.0
    volume_limit: 75
    quantity: 1
    call_strike_range_days: 25
    put_strike_range_days: 25
    expiry_min_days: 20
    expiry_max_days: 40
    max_strike_combinations: 4
    max_expiry_options: 8
    max_bid_ask_spread_call: 15.0
    max_bid_ask_spread_put: 15.0
    combo_buffer_percent: 0.0075
    slippage_model: "LINEAR"
    base_slippage_bps: 2                 # Lower slippage in calm markets
    liquidity_penalty_factor: 0.8       # Lower penalty in calm markets
    commission_per_contract: 1.00
    vix_regime_filter: "LOW"             # Only trade in low VIX
    min_vix_level: null
    max_vix_level: 20.0                  # Max VIX 20
    exclude_vix_spikes: true

  # High VIX environment optimization
  high_vix:
    profit_target: 1.00                  # Higher profit target in volatile markets
    cost_limit: 250.0                    # Higher cost tolerance
    volume_limit: 150                    # Higher volume requirement
    quantity: 1
    call_strike_range_days: 35           # Wider ranges for more opportunities
    put_strike_range_days: 35
    expiry_min_days: 15                  # Shorter expiries for faster profit
    expiry_max_days: 35
    max_strike_combinations: 5
    max_expiry_options: 6                # Fewer expiries, focus on quality
    max_bid_ask_spread_call: 25.0        # Allow wider spreads (higher volatility)
    max_bid_ask_spread_put: 25.0
    combo_buffer_percent: 0.015          # Larger buffer for execution
    slippage_model: "IMPACT"             # Impact model for volatile markets
    base_slippage_bps: 5                 # Higher slippage
    liquidity_penalty_factor: 1.5       # Higher penalty
    commission_per_contract: 1.25
    vix_regime_filter: "HIGH"            # Only trade in high VIX
    min_vix_level: 25.0                  # Min VIX 25
    max_vix_level: null
    exclude_vix_spikes: true             # Still exclude extreme spikes

  # Balanced configuration
  balanced:
    profit_target: 0.50
    cost_limit: 150.0
    volume_limit: 75
    quantity: 1
    call_strike_range_days: 25
    put_strike_range_days: 25
    expiry_min_days: 19
    expiry_max_days: 45
    max_strike_combinations: 4
    max_expiry_options: 8
    max_bid_ask_spread_call: 20.0
    max_bid_ask_spread_put: 20.0
    combo_buffer_percent: 0.01
    slippage_model: "LINEAR"
    base_slippage_bps: 3
    liquidity_penalty_factor: 1.0
    commission_per_contract: 1.00
    vix_regime_filter: null
    min_vix_level: null
    max_vix_level: null
    exclude_vix_spikes: false

# Slippage Models Configuration
slippage_models:
  NONE:
    description: "No slippage applied - theoretical best case"
    use_case: "Academic analysis, best-case scenarios"

  LINEAR:
    description: "Linear slippage model based on base rate + liquidity penalty"
    use_case: "Standard backtesting, moderate market conditions"
    formula: "base_slippage * (1 + liquidity_penalty)"

  SQUARE_ROOT:
    description: "Square root model for diminishing returns on liquidity penalty"
    use_case: "Markets with good liquidity infrastructure"
    formula: "base_slippage * sqrt(1 + liquidity_penalty)"

  IMPACT:
    description: "Market impact model considering trade size and liquidity"
    use_case: "Large trades, illiquid markets, realistic institutional trading"
    formula: "base_slippage * impact_factor * (1 + liquidity_penalty)"

# VIX Regime Definitions
vix_regimes:
  LOW:
    description: "Low volatility environment"
    range: "VIX < 15"
    characteristics: "Calm markets, lower option premiums, tighter bid-ask spreads"
    trading_impact: "More opportunities, lower profit per trade, easier execution"

  MEDIUM:
    description: "Normal volatility environment"
    range: "VIX 15-25"
    characteristics: "Normal market conditions, moderate option premiums"
    trading_impact: "Balanced opportunity set, moderate execution difficulty"

  HIGH:
    description: "High volatility environment"
    range: "VIX 25-35"
    characteristics: "Elevated volatility, higher option premiums, wider spreads"
    trading_impact: "Fewer but more profitable opportunities, harder execution"

  EXTREME:
    description: "Extreme volatility environment"
    range: "VIX > 35"
    characteristics: "Market stress, very high premiums, very wide spreads"
    trading_impact: "Rare but highly profitable opportunities, difficult execution"

# Performance Benchmarks
benchmarks:
  opportunity_discovery:
    excellent: "> 5 opportunities per day"
    good: "2-5 opportunities per day"
    fair: "0.5-2 opportunities per day"
    poor: "< 0.5 opportunities per day"

  execution_success:
    excellent: "> 90% success rate"
    good: "80-90% success rate"
    fair: "60-80% success rate"
    poor: "< 60% success rate"

  profitability:
    excellent: "> 2% average ROI"
    good: "1-2% average ROI"
    fair: "0.5-1% average ROI"
    poor: "< 0.5% average ROI"

  risk_metrics:
    excellent_sharpe: "> 2.0"
    good_sharpe: "1.0-2.0"
    fair_sharpe: "0.5-1.0"
    poor_sharpe: "< 0.5"

    low_drawdown: "< 2%"
    moderate_drawdown: "2-5%"
    high_drawdown: "5-10%"
    excessive_drawdown: "> 10%"

# Analysis Templates
analysis_templates:
  quick_performance:
    description: "Fast 30-day performance check"
    period: 30
    config: "balanced"
    symbols: ["SPY", "QQQ", "AAPL"]
    analysis_type: "single"

  comprehensive_1year:
    description: "Full 1-year comprehensive analysis"
    period: 365
    config: "conservative"
    symbols: ["SPY", "QQQ", "AAPL", "MSFT", "NVDA"]
    analysis_type: "comparative"

  market_regime_analysis:
    description: "Performance across different market regimes"
    period: 1825  # 5 years
    config: "balanced"
    symbols: ["SPY", "QQQ", "AAPL", "MSFT"]
    analysis_type: "vix"

  execution_model_comparison:
    description: "Compare different execution/slippage models"
    period: 365
    config: "balanced"
    symbols: ["SPY", "QQQ"]
    analysis_type: "slippage"

  strategy_optimization:
    description: "Multi-configuration optimization study"
    period: 1095  # 3 years
    configs: ["conservative", "aggressive", "balanced"]
    symbols: ["SPY", "QQQ", "AAPL", "MSFT", "NVDA", "TSLA"]
    analysis_type: "comparative"

# Output Configuration
output:
  # Console output formatting
  console:
    use_rich_formatting: true
    show_progress_bars: true
    detailed_tables: true
    color_coding: true

  # File export options
  export:
    formats: ["json", "csv", "xlsx"]
    include_raw_data: false
    include_trade_details: true
    include_rejection_analysis: true

  # Database storage
  database_storage:
    store_opportunities: true
    store_trades: true
    store_rejections: true
    store_analytics: true
    cleanup_old_runs: false  # Keep historical runs for analysis

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_logging: false
  log_file_path: "logs/sfr_backtest.log"
  max_file_size: "10MB"
  backup_count: 5

# Performance Optimization
performance:
  # Database query optimization
  batch_size: 1000
  connection_pool_size: 20
  query_timeout_seconds: 30

  # Memory management
  max_opportunities_in_memory: 10000
  max_trades_in_memory: 5000
  periodic_memory_cleanup: true

  # Parallel processing
  max_concurrent_symbols: 4
  max_concurrent_days: 2
  async_processing: true

# Validation Rules
validation:
  # Data quality checks
  min_stock_price: 10.0
  max_stock_price: 1000.0
  min_option_price: 0.01
  max_option_price: 100.0
  max_bid_ask_spread_percent: 50.0

  # Logical consistency checks
  require_positive_net_credit: true
  require_call_strike_above_put: true
  max_days_to_expiry: 365
  min_days_to_expiry: 1

  # Risk limits
  max_single_trade_loss: 1000.0
  max_portfolio_exposure: 100000.0
  max_symbol_concentration: 0.20  # 20% max in single symbol
