version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: alc_timescaledb
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=options_arbitrage
      - POSTGRES_USER=trading_user
      - POSTGRES_PASSWORD=secure_trading_password
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=en_US.UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../schema:/docker-entrypoint-initdb.d:ro
      - ./00-init-timescaledb.sh:/docker-entrypoint-initdb.d/00-init-timescaledb.sh:ro
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trading_user -d options_arbitrage"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - alc_network

volumes:
  postgres_data:

networks:
  alc_network:
    driver: bridge
