# Historical Data Loading Pipeline Configuration
# This file contains default settings for the data loading pipeline.
# These can be overridden by environment variables or command-line arguments.

# Database connection settings
database:
  host: localhost
  port: 5432
  database: options_arbitrage
  user: trading_user
  password: secure_trading_password
  min_pool_size: 5
  max_pool_size: 20

# Interactive Brokers connection settings
ib_connection:
  host: 127.0.0.1
  port: 7497
  client_id: 1
  timeout: 30

# Data loading configuration
loading:
  # Number of symbols to process in parallel
  batch_size: 10

  # Delay between IB API requests (seconds)
  request_delay: 0.5

  # Number of retry attempts for failed requests
  retry_attempts: 3

  # Maximum days to request in a single IB API call
  max_days_per_request: 30

  # Bar size for historical data
  # Valid values: 1 secs, 5 secs, 10 secs, 15 secs, 30 secs, 1 min, 2 mins, 3 mins,
  #               5 mins, 10 mins, 15 mins, 20 mins, 30 mins, 1 hour, 2 hours, 3 hours,
  #               4 hours, 8 hours, 1 day, 1W, 1M
  bar_size: "1 min"

  # What data to show
  # Valid values: TRADES, MIDPOINT, BID, ASK, BID_ASK, HISTORICAL_VOLATILITY, OPTION_IMPLIED_VOLATILITY
  what_to_show: "MIDPOINT"

  # Use regular trading hours only
  use_rth: true

  # Retry delay in seconds
  retry_delay: 10.0

# Data validation settings
validation:
  # Enable data validation during loading
  enabled: true

  # Maximum bid-ask spread as percentage of mid price
  max_spread_percent: 0.1

  # Data quality threshold (0.0 to 1.0)
  quality_threshold: 0.5

  # Validate Greeks bounds
  validate_greeks: true

  # Maximum acceptable IV level
  max_implied_volatility: 10.0

# Logging configuration
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: INFO

  # Log file path (null for no file logging)
  file: null

  # Log format
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  # Enable rich console formatting
  rich_console: true

  # Show tracebacks in rich format
  rich_tracebacks: true

# Default symbols for bulk operations
default_symbols:
  - SPY
  - QQQ
  - IWM
  - DIA
  - AAPL
  - MSFT
  - GOOGL
  - AMZN
  - TSLA
  - META
  - NVDA
  - AMD

# Options chain filtering
options:
  # Days ahead to collect options data
  expiry_range_days: 60

  # Percentage range around ATM (e.g., 0.20 = ±20%)
  strike_range_percent: 0.20

  # Minimum volume filter
  min_volume: 0

  # Minimum open interest filter
  min_open_interest: 0

  # Maximum number of contracts to process per symbol
  max_contracts_per_symbol: 100

# Performance tuning
performance:
  # Connection pool settings
  db_pool_size: 20

  # Maximum concurrent IB requests
  max_concurrent_requests: 5

  # Request throttling (requests per minute)
  max_requests_per_minute: 60

  # Chunk size for database inserts
  db_insert_chunk_size: 1000

  # Memory usage limits
  max_memory_mb: 2048

# Error handling
error_handling:
  # Stop pipeline on critical errors
  stop_on_critical_error: false

  # Maximum errors per symbol before skipping
  max_errors_per_symbol: 5

  # Retry exponential backoff settings
  retry_base_delay: 1.0
  retry_max_delay: 60.0
  retry_multiplier: 2.0

# Progress reporting
progress:
  # Update interval for progress bars (seconds)
  update_interval: 1.0

  # Show detailed statistics
  show_detailed_stats: true

  # Save progress to file for resume capability
  save_progress: false
  progress_file: "pipeline_progress.json"
